Repository boostcampwm-2024/web06-harmony, pull requests merged in 2024-11, with the labels that each got.

#37 [Feat] 서버 개발 환경을 구축한다.
  apps/server/config/typeorm.config.ts
  apps/server/package.json
  apps/server/src/app.module.ts
Labels: Config, BE

#48 [Docs] README.md 링크 갱신
  README.md
Labels: Docs

#39 [Feat] 태스크 생성 API 구현
  apps/server/config/typeorm.config.ts
  apps/server/package.json
  apps/server/src/app.module.ts
  apps/server/src/task/controller/task.controller.ts
  apps/server/src/task/domain/section.entity.ts
  apps/server/src/task/domain/task.entity.ts
  apps/server/src/task/dto/create-task-request.dto.ts
  apps/server/src/task/dto/create-task-response.dto.ts
  apps/server/src/task/repository/task.repository.ts
  apps/server/src/task/service/task.service.ts
  apps/server/src/task/task.module.ts
  pnpm-lock.yaml
Labels: Feature, BE

#50 [Config] 배포를 위한 서버 환경 변수 설정 스크립트 추가
  .github/workflows/ci-cd.yml
Labels: Config

#52 [Feat] 태스크 수정 API 구현
  apps/server/src/task/controller/task.controller.ts
  apps/server/src/task/dto/update-task-request.dto.ts
  apps/server/src/task/dto/update-task-response.dto.ts
  apps/server/src/task/repository/task.repository.ts
  apps/server/src/task/service/task.service.ts
  pnpm-lock.yaml
Labels: Feature, BE

#60 [Feat] 단일 태스크 조회 API 구현
  apps/server/src/task/controller/task.controller.ts
  apps/server/src/task/dto/task-response.dto.ts
  apps/server/src/task/service/task.service.ts
Labels: Refactor, Feature, BE

#66 [Feat] 프로젝트 동적 라우팅 생성
  apps/client/src/routeTree.gen.ts
  apps/client/src/routes/_auth.$project.board.tsx
  apps/client/src/routes/_auth.$project.index.tsx
  apps/client/src/routes/_auth.$project.settings.tsx
  apps/client/src/routes/_auth.$project.tsx
  apps/client/src/routes/_auth.tsx
Labels: Feature, FE

#67 [Feat] 태스크 삭제 API 구현
  apps/server/src/task/controller/task.controller.ts
  apps/server/src/task/dto/delete-task-response.dto.ts
  apps/server/src/task/service/task.service.ts
Labels: Feature, BE

#69 [Feat] 프로젝트 별 태스크 목록 조회 API 구현
  apps/server/src/project/controller/project.controller.ts
  apps/server/src/project/service/project.service.ts
  apps/server/src/task/controller/task.controller.ts
  apps/server/src/task/domain/section.entity.ts
  apps/server/src/task/dto/create-task-request.dto.ts
  apps/server/src/task/service/task.service.ts
Labels: Feature, BE

#73 [BugFix] 서버 엔티티 의존성 문제 해결
  apps/server/src/project/project.module.ts
  apps/server/src/task/task.module.ts
Labels: BugFix, BE

#82 [Feat] 프로젝트 생성시 기본 섹션 추가 생성
  apps/server/.eslintrc.js
  apps/server/src/account/account.module.ts
  apps/server/src/account/controller/account.controller.ts
  apps/server/src/account/dto/user.dto.ts
  apps/server/src/account/service/account.service.ts
  apps/server/src/account/service/auth.service.ts
  apps/server/src/account/strategy/accessToken.strategy.ts
  apps/server/src/account/strategy/refreshToken.strategy.ts
  apps/server/src/app.controller.spec.ts
  apps/server/src/app.controller.ts
  apps/server/src/app.module.ts
  apps/server/src/main.ts
  apps/server/src/project/controller/project.controller.ts
  apps/server/src/project/controller/projects.controller.ts
  apps/server/src/project/dto/create-project-response.dto.ts
  apps/server/src/project/dto/project-contributors-response-dto.ts
  apps/server/src/project/dto/update-contributor-request.dts.ts
  apps/server/src/project/dto/user-projects-response.dto.ts
  apps/server/src/project/entity/contributor.entity.ts
  apps/server/src/project/project.module.ts
  apps/server/src/project/service/project.service.ts
  apps/server/src/task/controller/snapshot.controller.ts
  apps/server/src/task/controller/task.controller.ts
  apps/server/src/task/domain/snapshot.ts
  apps/server/src/task/domain/task.entity.ts
  apps/server/src/task/dto/create-task-response.dto.ts
  apps/server/src/task/dto/move-task-response.dto.ts
  apps/server/src/task/dto/task-response.dto.ts
  apps/server/src/task/dto/update-task-response.dto.ts
  apps/server/src/task/service/task.service.ts
  apps/server/src/task/task.module.ts
Labels: Refactor, Feature, BE

#84 [Feat] 스냅샷 갱신 후에 섹션 변경 사항이 적용되지 않는 문제 해결
  apps/server/src/common/allException.filter.ts
  apps/server/src/task/domain/snapshot.ts
  apps/server/src/task/dto/update-task-request.dto.ts
  apps/server/src/task/service/task.service.ts
Labels: BugFix, BE

#101 새로고침의 경우에도 로그인 상태 유지하기
  apps/client/src/contexts/authContext.tsx
Labels: Feature, FE

#104 [Feat] 변경 발생 이벤트를 브로드캐스트 하는 기능 구현
  apps/server/.eslintrc.js
  apps/server/src/app.module.ts
  apps/server/src/project/controller/project.controller.ts
  apps/server/src/task/controller/event.controller.ts
  apps/server/src/task/controller/task.controller.ts
  apps/server/src/task/domain/snapshot.ts
  apps/server/src/task/domain/update-information.type.ts
  apps/server/src/task/dto/create-task-request.dto.ts
  apps/server/src/task/dto/move-task-request.dto.ts
  apps/server/src/task/dto/task-event-response.dto.ts
  apps/server/src/task/dto/task-event.dto.ts
  apps/server/src/task/dto/update-task-request.dto.ts
  apps/server/src/task/service/broadcast.service.ts
  apps/server/src/task/service/task.service.ts
  apps/server/src/task/task.module.ts
Labels: Feature, BE

#111 [Feat] 초대받은 프로젝트 목록 조회, 승인/거절 기능 구현
  apps/client/src/pages/AccountSettings.tsx
  apps/client/src/routes/_auth.account.settings.tsx
  apps/client/src/types/project.ts
Labels: Feature, FE

#117 [Fix] 링크를 버튼으로 수정
  apps/client/src/routes/_auth.tsx
Labels: BugFix, FE

#127 [BugFix] 플래닝 포커 Socket API 문제 해결
  apps/server/src/planning-poker/gateway/planning-poker.gateway.ts
Labels: BugFix, BE

#129 [BugFix] 플래닝 포커 Socket API 연동 문제 해결
  apps/server/src/planning-poker/gateway/planning-poker.gateway.ts
Labels: BugFix, BE

#131 [BugFix] handleDisconnect에서 userId를 잘못 조회하는 문제 해결
  apps/server/src/planning-poker/gateway/planning-poker.gateway.ts
Labels: BugFix, BE

#133 [BugFix] Socket.IO 에서 disconnect 시, rooms에서 자동 삭제되는 이슈 해결
  apps/server/src/planning-poker/gateway/planning-poker.gateway.ts
Labels: BugFix, BE

#138 [Feat] users_fetched 이벤트 응답 시, 카드 선택 여부 및 reveal 여부 전송 기능 추가
  apps/server/src/planning-poker/gateway/planning-poker.gateway.ts
Labels: Feature, BE

#140 [BugFix] reset_card 및 room에서 모든 사용자가 disconnect 했을 경우, isRevealed 초기화
  apps/server/src/planning-poker/gateway/planning-poker.gateway.ts
Labels: BugFix, BE

#147 계정 설정 페이지에 접근할 수 없는 오류 수정
  apps/client/src/components/KanbanBoard.tsx
  apps/client/src/routes/_auth.account.settings.tsx
Labels: BugFix, FE

#153 [Fix] Description word-break 이슈 수정
  apps/client/src/features/task/components/TaskDescription.tsx
  apps/client/src/features/task/subtask/components/Subtasks.tsx
Labels: BugFix, FE

#160 [BugFix] CD 과정에서 .env에 환경 변수가 계속해서 누적되고 있던 문제 해결
  .github/workflows/CD.yaml
Labels: BugFix, Config

#169 [BugFix] presigned url 생성 시, public ACL 설정 추가
  apps/server/src/image/service/image.service.ts
Labels: BugFix, BE

#171 [BugFix] access-url 생성 시, http:// 가 2번 포함되는 문제 해결
  apps/server/src/account/entity/account.entity.ts
  apps/server/src/image/service/image.service.ts
Labels: BugFix, BE

#177 [Fix] axios base url 삽입
  apps/client/src/features/auth/api.ts
Labels: BugFix, FE

#182 [Feat] 대시보드 기능 분할
  apps/server/src/project/controller/project.controller.ts
  apps/server/src/task/service/task.service.ts
Labels: Feature, BE

#184 [BugFix] 워크로드 쿼리 오류 수정
  apps/server/src/task/service/task.service.ts
Labels: BugFix, BE

#175 [Feat] User 검색 API 구현
  apps/server/src/account/account.module.ts
  apps/server/src/account/user.controller.ts
  apps/server/src/account/user.service.ts
Labels: Feature, BE

#192 [Feat] 대시보드 우선순위 통계 기능 구현
  apps/server/src/image/controller/image.controller.ts
  apps/server/src/image/service/image.service.ts
  apps/server/src/project/controller/project.controller.ts
  apps/server/src/task/service/task.service.ts
Labels: Feature, BE

#194 [BugFix] 태스크 조회시 유저 프로필 누락 수정
  apps/server/src/task/service/task.service.ts
Labels: BugFix, BE

#199 [Feat] https로 변경됨에 따라, CORS 설정 변경
  apps/server/src/common/socket-adapter/custom-io-adapter.ts
Labels: Config, BE

#205 [BugFix] https로 변경 후, 프로필 이미지 수정 시 CORS 발생 문제 해결
  apps/server/src/account/user.controller.ts
  apps/server/src/image/service/image.service.ts
Labels: BugFix, BE
