Repository boostcampwm-2024/web06-harmony, pull requests merged in 2024-12, with the labels that each got.

#213 [Feat] 단일 이벤트가 아닌 여러 이벤트 브로드캐스트
  apps/server/src/project/dto/invite-user-request.dto.ts
  apps/server/src/project/service/project.service.ts
  apps/server/src/task/controller/event.controller.ts
  apps/server/src/task/domain/custom-response.interface.ts
  apps/server/src/task/dto/task-event-response.dto.ts
  apps/server/src/task/enum/eventType.enum.ts
  apps/server/src/task/event/title-updated.event.ts
  apps/server/src/task/service/broadcast.service.ts
  apps/server/src/task/service/task.service.ts
Labels: Feature, BE

#221 header 컴포넌트 리팩토링
  apps/client/src/components/Header.tsx
  apps/client/src/components/navigation/topbar.tsx
  apps/client/src/pages/Home.tsx
  apps/client/src/pages/Login.tsx
  apps/client/src/pages/Signup.tsx
  apps/client/src/routes/_auth.tsx
Labels: Refactor, FE

#223 각각의 쿼리에 대해 useSuspenseQuries로 수정
  apps/client/src/pages/ProjectOverview.tsx
  apps/client/src/routes/_auth.$project.index.tsx
Labels: Refactor, FE

#234 [BugFix] 외부 편집 사항이 내 편집사항을 덮어쓰는 문제 해결
  apps/client/src/features/project/board/components/KanbanBoard.tsx
  apps/client/src/features/project/board/useBoardStore.ts
Labels: BugFix
